### ISSUE TITLE
Metadata standaard AR: Identificatie

### ISSUE THREAD

**Issue by batena541** [Algoritmeregister/algoritmeregister-metadata-standaard#6]
Ik mis de unieke identificatie van het algoritme. De invulling hangt ook af van de keuze of er een landelijke catalogus komt of een verzameling van lokale catalogi. In het laatste geval zou je kunnen kiezen voor Lokale catalogus + Lokale identificatie van het algoritme. Het is ook te overwegen om een AKN-achtige-identificatie te gebruiken. Je maakt een algoritme dan uniek door de combinatie van Identificatie van bevoegd gezag + lokale identificatie van het algoritme. Je moet dan samen afspraken maken over de opbouw van de AKN-achtige-identificatie. Dit kan er bijvoorbeeld zo uitzien: /akn/nl/arpub/pv28/2018/reg003 .
arpub staat voor algoritme publicatie en pv28 is de landelijke code van provincie Zuid-Holland, wat daarachter volgt is een lokale identificatie.

**Comment by jgroenen** [comment]
Ik gebruik nu https://nl.wikipedia.org/wiki/Universally_unique_identifier voor de toepassing. Informatie over de organisatie zou ik in een daarvoor bestemde veld zetten (zie ook https://github.com/Algoritmeregister/algoritmeregister-metadata-standaard/issues/4).

**Comment by batena541** [comment]
Je gaat dan uit van een centrale uitgifte waarmee je de uniciteit kan borgen? Door een AKN-achtige naamgevingsconventie te hanteren maak je een decentrale uitgifte van de unieke identificatie mogelijk. We hebben geen uitspraak gedaan of we een centrale registratie functie nastreven of juist een decentrale registratie.
